// <auto-generated />
using AICommunicationService.DAL.Context.AiCommunication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AICommunicationService.DAL.Migrations
{
    [DbContext(typeof(AICommunicationContext))]
    [Migration("20230918115043_AddInputField")]
    partial class AddInputField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AICommunicationService.DAL.Models.AIPrompt", b =>
                {
                    b.Property<string>("TamplateName")
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TamplateName");

                    b.ToTable("AIPrompts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
