name: Build and deploy API Gateway
on:
  push:
    branches:
      - 'customer_7653'
    paths:
      - OcelotApiGateway/**
      - .github/workflows/DeployGateway.yml

env:
  ENVNAME: ${{ vars.ENVNAME }} 
  AZURE_WEBAPP_NAME: 'EllogyGateway-7653'

jobs:
  build_api_gateway:
    permissions: write-all
    
    env:  
      MICROSERVICE_NAME: 'api_gateway'
      PROJECT_PATH: './OcelotApiGateway/'
      CONTEXT: '.'
      DOCKERFILEPATH: './OcelotApiGateway/Dockerfile'

    outputs:
      MicroserviceName: ${{ steps.build-n-push.outputs.MicroserviceName }}
      MicroserviceImage: ${{ steps.build-n-push.outputs.MicroserviceImage }}

    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Build and push image of API Gateway
        id: build-n-push
        uses: ./.github/actions/Build-n-push
        with: 
          MicroserviceName: ${{ env.MICROSERVICE_NAME }}
          Environment: ${{ env.ENVNAME }}
          ProjectPath: ${{ env.PROJECT_PATH }}
          Context: ${{ env.CONTEXT }}
          DockerfilePath: ${{ env.DOCKERFILEPATH }}
          Token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    needs: build_api_gateway

    env:
      URL: ${{ needs.build_api_gateway.outputs.MicroserviceImage }}

    steps:
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get WebApp/FunctionApp publish profile
        id: webapp
        uses: aliencube/publish-profile-actions@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_7653 }}
        with:
          resourceGroupName: 'Ellogy_7653'
          appName: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: '${{ steps.webapp.outputs.profile }}'
          images: 'ghcr.io/${{ env.URL }}'
